"""PDF export utility for DevHandoff architectural transition documents."""

from __future__ import annotations

import io
import re
from datetime import datetime
from reportlab.lib.pagesizes import letter
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    HRFlowable,
    KeepTogether,
    Preformatted,
)
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors
from reportlab.pdfgen import canvas


class NumberedCanvas(canvas.Canvas):
    """Two-pass canvas to dynamically compute and print total page count."""

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._saved_page_states = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_page_decorations(num_pages)
            super().showPage()
        super().save()

    def draw_page_decorations(self, page_count: int):
        self.saveState()
        self.setFont("Helvetica", 8)
        self.setFillColor(colors.HexColor("#64748b"))

        # Running header (pages > 1)
        if self._pageNumber > 1:
            self.drawString(40, 760, "DevHandoff // Architectural Transition Report")
            self.setStrokeColor(colors.HexColor("#cbd5e1"))
            self.setLineWidth(0.5)
            self.line(40, 752, 572, 752)

        # Running footer
        page_str = f"Page {self._pageNumber} of {page_count}"
        self.drawRightString(572, 30, page_str)
        self.drawString(40, 30, "Generated by DevHandoff &bull; Synthesized by IBM watsonx.ai")
        self.setStrokeColor(colors.HexColor("#cbd5e1"))
        self.setLineWidth(0.5)
        self.line(40, 42, 572, 42)

        self.restoreState()


def _clean_markdown_to_xml(text: str) -> str:
    """Escape XML special chars and convert basic Markdown styling to ReportLab HTML tags."""
    # First escape &, <, >
    text = text.replace("&", "&amp;")
    text = text.replace("<", "&lt;").replace(">", "&gt;")

    # Re-allow safe styling tags that we convert from markdown
    # Bold **text** -> <b>text</b>
    text = re.sub(r"\*\*(.+?)\*\*", r"<b>\1</b>", text)
    # Italic *text* -> <i>text</i>
    text = re.sub(r"(?<!\*)\*(?!\*)(.+?)(?<!\*)\*(?!\*)", r"<i>\1</i>", text)
    # Monospace `code` -> <font name='Courier'>code</font>
    text = re.sub(r"`([^`]+)`", r"<font name='Courier' color='#0284c7'><b>\1</b></font>", text)

    return text


def generate_handoff_pdf(
    handoff_markdown: str,
    repo_name: str = "Repository",
    branch: str = "master",
    generated_at: str | None = None,
) -> bytes:
    """Convert DevHandoff synthesized markdown report into a polished, professional PDF."""
    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf,
        pagesize=letter,
        leftMargin=40,
        rightMargin=40,
        topMargin=48,
        bottomMargin=54,
    )

    styles = getSampleStyleSheet()

    # Custom palette
    primary_color = colors.HexColor("#0f172a")
    brand_blue = colors.HexColor("#0284c7")
    accent_purple = colors.HexColor("#7c3aed")
    text_color = colors.HexColor("#1e293b")
    meta_color = colors.HexColor("#475569")
    code_bg = colors.HexColor("#f8fafc")

    # Typography styles
    title_style = ParagraphStyle(
        "DocTitle",
        parent=styles["Normal"],
        fontName="Helvetica-Bold",
        fontSize=24,
        leading=28,
        textColor=primary_color,
        spaceAfter=4,
    )

    subtitle_style = ParagraphStyle(
        "DocSubtitle",
        parent=styles["Normal"],
        fontName="Helvetica",
        fontSize=11,
        leading=15,
        textColor=meta_color,
        spaceAfter=14,
    )

    meta_badge_style = ParagraphStyle(
        "MetaBadge",
        parent=styles["Normal"],
        fontName="Helvetica-Bold",
        fontSize=9,
        leading=12,
        textColor=brand_blue,
        spaceAfter=14,
    )

    h1_style = ParagraphStyle(
        "SectionH1",
        parent=styles["Normal"],
        fontName="Helvetica-Bold",
        fontSize=14,
        leading=18,
        textColor=accent_purple,
        spaceBefore=14,
        spaceAfter=6,
        keepWithNext=True,
    )

    h2_style = ParagraphStyle(
        "SectionH2",
        parent=styles["Normal"],
        fontName="Helvetica-Bold",
        fontSize=11,
        leading=15,
        textColor=primary_color,
        spaceBefore=10,
        spaceAfter=4,
        keepWithNext=True,
    )

    body_style = ParagraphStyle(
        "BodyDark",
        parent=styles["Normal"],
        fontName="Helvetica",
        fontSize=9.5,
        leading=14,
        textColor=text_color,
        spaceAfter=6,
    )

    bullet_style = ParagraphStyle(
        "BulletText",
        parent=body_style,
        leftIndent=14,
        firstLineIndent=-10,
        spaceAfter=3,
    )

    code_style = ParagraphStyle(
        "CodeText",
        parent=styles["Normal"],
        fontName="Courier",
        fontSize=8,
        leading=11,
        textColor=colors.HexColor("#0f172a"),
        backColor=code_bg,
        borderPadding=6,
        spaceBefore=4,
        spaceAfter=6,
    )

    story = []

    # Title block
    story.append(Paragraph("DevHandoff", title_style))
    story.append(Paragraph("Architectural & Knowledge Transition Report", ParagraphStyle(
        "HandoffSub", parent=title_style, fontSize=16, leading=20, textColor=brand_blue, spaceAfter=8
    )))

    ts = generated_at or datetime.now().strftime("%Y-%m-%d %H:%M:%S UTC")
    meta_info = f"<b>Target Repository:</b> {repo_name} &nbsp;|&nbsp; <b>Branch:</b> {branch} &nbsp;|&nbsp; <b>Timestamp:</b> {ts}"
    story.append(Paragraph(meta_info, subtitle_style))
    story.append(Paragraph("AI-Synthesized via IBM watsonx.ai (meta-llama/llama-3-3-70b-instruct) on IBM Cloud", meta_badge_style))
    story.append(HRFlowable(width="100%", thickness=1.5, color=brand_blue, spaceAfter=14))

    # Parse and build sections
    lines = handoff_markdown.splitlines()
    in_code_block = False
    code_lines = []

    for line in lines:
        stripped = line.strip()

        # Handle code fences
        if stripped.startswith("```"):
            if in_code_block:
                in_code_block = False
                code_text = "\n".join(code_lines)
                if code_text.strip():
                    story.append(Preformatted(code_text, code_style))
                code_lines = []
            else:
                in_code_block = True
                code_lines = []
            continue

        if in_code_block:
            code_lines.append(line)
            continue

        if not stripped:
            story.append(Spacer(1, 4))
            continue

        # Horizontal rules
        if stripped in ("---", "***", "___"):
            story.append(Spacer(1, 4))
            story.append(HRFlowable(width="100%", thickness=0.5, color=colors.HexColor("#e2e8f0"), spaceAfter=8))
            continue

        # Headings
        if stripped.startswith("# "):
            clean_text = _clean_markdown_to_xml(stripped[2:])
            story.append(Spacer(1, 10))
            story.append(Paragraph(clean_text, h1_style))
            continue
        elif stripped.startswith("## "):
            clean_text = _clean_markdown_to_xml(stripped[3:])
            story.append(Spacer(1, 8))
            story.append(Paragraph(clean_text, h1_style))
            story.append(HRFlowable(width="100%", thickness=0.8, color=colors.HexColor("#cbd5e1"), spaceAfter=6))
            continue
        elif stripped.startswith("### "):
            clean_text = _clean_markdown_to_xml(stripped[4:])
            story.append(Paragraph(clean_text, h2_style))
            continue

        # Bullets
        if stripped.startswith(("- ", "* ", "+ ")):
            bullet_content = _clean_markdown_to_xml(stripped[2:])
            story.append(Paragraph(f"&bull; {bullet_content}", bullet_style))
            continue

        # Numbered lists (e.g. "1. ")
        num_match = re.match(r"^(\d+)\.\s+(.*)$", stripped)
        if num_match:
            num = num_match.group(1)
            content = _clean_markdown_to_xml(num_match.group(2))
            story.append(Paragraph(f"<b>{num}.</b> {content}", bullet_style))
            continue

        # Regular text
        xml_text = _clean_markdown_to_xml(stripped)
        story.append(Paragraph(xml_text, body_style))

    # Flush any unclosed code block
    if in_code_block and code_lines:
        story.append(Preformatted("\n".join(code_lines), code_style))

    doc.build(story, canvasmaker=NumberedCanvas)
    return buf.getvalue()
